#! /bin/bash

die () {
	echo >&2 "$@"
	exit 1
}

# Checking arguments
if [[ -z "$1" || -z "$2" || -z "$3" ]]; then
	die "Usage: `basename $0` width input.svg output.png"
fi

# checking for inkscape
PKG_OK=$(dpkg-query -W --showformat='${Status}\n' inkscape|grep "install ok installed")
if [[ "" == "$PKG_OK" ]]; then
	die "Inkscape in needed, please run: sudo apt-get install inkscape"
fi

# check a folder
check_folder() {
	if [[ ! -e $1 ]]; then
		mkdir -p $1
	elif [[ ! -d $1 ]]; then
		die "$1 is not a folder... please check it"
	fi
}

base_width=$1
input_file=$2
output_file=$3

svg2png () {
	resource_width=$(echo $base_width*$1 | bc)
	resource_folder=$2
	check_folder $resource_folder
	inkscape -z -w $resource_width -e $resource_folder/$output_file $input_file > /dev/null 2>&1
}

# The needed android resource sizes
dpi=(0.75 1 1.5 2 3 4)

# The folders matching the resource sizes
res_folders=( 'drawable-ldpi' 'drawable-mdpi' 'drawable-hdpi' 'drawable-xhdpi' 'drawable-xxhdpi' 'drawable-xxxhdpi')

total=${#dpi[*]}

for (( i=0; i<=$(( $total -1 )); i++ )); do
	svg2png ${dpi[$i]} ${res_folders[$i]}
done
