#! /bin/bash

die () {
	echo >&2 "$@"
	exit 1
}

# Checking arguments
if [[ -z "$1" || -z "$2" || -z "$3" ]]; then
	die "Usage: `basename $0` width input.svg output.png"
fi

# checking for inkscape
PKG_OK=$(dpkg-query -W --showformat='${Status}\n' inkscape|grep "install ok installed")
if [[ "" == "$PKG_OK" ]]; then
	die "Inkscape in needed, please run: sudo apt-get install inkscape"
fi

base_width=$1
input_file=$2
output_file=$3

# The needed android resource sizes
dpi=(0.75 1 1.5 2 3 4)

# The folders matching the resource sizes
folder=( 'ldpi' 'mdpi' 'hdpi' 'xhdpi' 'xxhdpi' 'xxxhdpi')

svg2png () {
	resource_width=$(echo $base_width*${dpi[$1]} | bc)
	resource_folder=${folder[$1]}
	if [[ ! -e $resource_folder ]]; then
		mkdir -p $resource_folder
	elif [[ ! -d $resource_folder ]]; then
		die "$resource_folder is not a folder... please check it"
	fi
	inkscape -z -w $resource_width -e $resource_folder/$output_file $input_file > /dev/null 2>&1
}

total=${#dpi[*]}

for (( i=0; i<=$(( $total -1 )); i++ )); do
	svg2png $i
done
